import type { AgentPolicy } from "../types.js";
import type { AgentConfig, DriverConfig, GatewayConfig } from "./types.js";
export const MODEL_PATTERN = /^[a-z0-9][a-z0-9._-]{0,127}$/i;
const MODEL_SUPPORTED_KINDS = new Set(["agy", "codex", "opencode"]);
const object = (value: unknown): Record<string, unknown> | undefined => typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : undefined;
const extras = (value: Record<string, unknown>, keys: readonly string[], where: string): void => { for (const key of Object.keys(value)) if (!keys.includes(key)) throw new Error(`${where} has unknown field '${key}'`); };
const string = (value: unknown, where: string): string => { if (typeof value !== "string" || value.length === 0) throw new Error(`${where} must be a non-empty string`); return value; };
const positive = (value: unknown, where: string): number => { if (typeof value !== "number" || !Number.isFinite(value) || value <= 0 || value > 2147483647) throw new Error(`${where} must be a reasonable positive number`); return value; };
const choice = <T extends string>(value: unknown, options: readonly T[], where: string): T => { if (typeof value !== "string" || !options.includes(value as T)) throw new Error(`${where} is invalid`); return value as T; };
const customizationName = (value: unknown, where: string): string | undefined => { if (value === undefined || value === null || value === "") return undefined; const name = string(value, where); if (!/^[a-z0-9][a-z0-9-]{0,63}$/.test(name)) throw new Error(`${where} is invalid`); return name; };
function policy(value: unknown): AgentPolicy { const p = object(value); if (!p) throw new Error("agent policy must be an object"); extras(p, ["filesystem", "network", "credentials", "process"], "agent policy"); return { filesystem: choice(p.filesystem, ["none", "read-only", "workspace-write"], "policy.filesystem"), network: choice(p.network, ["deny", "allow"], "policy.network"), credentials: choice(p.credentials, ["deny", "inherited-approved"], "policy.credentials"), process: choice(p.process, ["deny-shell", "driver-default"], "policy.process") }; }
export function validateConfig(value: unknown): GatewayConfig {
 const root = object(value); if (!root) throw new Error("config must be an object"); extras(root, ["$schema", "version", "defaults", "allowedWorkspaceRoots", "drivers", "agents"], "config"); if (root.version !== 1) throw new Error("config.version must be 1");
 const rawDefaults = root.defaults === undefined ? {} : object(root.defaults); if (!rawDefaults) throw new Error("defaults must be an object"); extras(rawDefaults, ["timeoutSeconds", "maxOutputBytes", "maxConcurrency"], "defaults"); const defaults = { ...(rawDefaults.timeoutSeconds === undefined ? {} : { timeoutSeconds: positive(rawDefaults.timeoutSeconds, "defaults.timeoutSeconds") }), ...(rawDefaults.maxOutputBytes === undefined ? {} : { maxOutputBytes: positive(rawDefaults.maxOutputBytes, "defaults.maxOutputBytes") }), ...(rawDefaults.maxConcurrency === undefined ? {} : { maxConcurrency: positive(rawDefaults.maxConcurrency, "defaults.maxConcurrency") }) };
 const rawDrivers = object(root.drivers); if (!rawDrivers) throw new Error("drivers must be an object"); const drivers: Record<string, DriverConfig> = {}; for (const [id, raw] of Object.entries(rawDrivers)) { const d = object(raw); if (!d) throw new Error(`driver '${id}' must be an object`); extras(d, ["kind", "command", "script"], `driver '${id}'`); const kind = string(d.kind, "driver.kind"); if (kind !== "fake" && kind !== "agy" && kind !== "codex" && kind !== "opencode") throw new Error(`driver '${id}' has unsupported kind`); drivers[id] = { kind, command: string(d.command, "driver.command"), ...(d.script === undefined ? {} : { script: string(d.script, "driver.script") }) }; }
 if (!Array.isArray(root.agents)) throw new Error("agents must be an array"); const names = new Set<string>(); const agents: AgentConfig[] = root.agents.map((raw, i) => { const a = object(raw); if (!a) throw new Error(`agent ${i} must be object`); extras(a, ["name", "label", "description", "driver", "purposes", "policy", "promptContract", "agent", "requiredSkill", "defaults", "enabled"], `agent ${i}`); const name = string(a.name, "agent.name"); if (!/^[a-z0-9][a-z0-9-]{0,63}$/.test(name) || names.has(name)) throw new Error("agent name is invalid or duplicated"); names.add(name); const driver = string(a.driver, "agent.driver"); const driverConfig = drivers[driver]; if (!driverConfig) throw new Error(`agent '${name}' references missing driver`); if (!Array.isArray(a.purposes) || a.purposes.some((x) => typeof x !== "string")) throw new Error("agent purposes must be strings"); if (typeof a.enabled !== "boolean") throw new Error("agent enabled must be boolean"); let d: AgentConfig["defaults"]; if (a.defaults !== undefined) { const x = object(a.defaults); if (!x) throw new Error("agent defaults must be object"); extras(x, ["effort", "timeoutSeconds", "model"], "agent defaults"); let model: string | undefined; if (x.model !== undefined) { if (typeof x.model !== "string") throw new Error("model is invalid"); model = x.model.trim(); if (!MODEL_PATTERN.test(model)) throw new Error("model is invalid"); if (!MODEL_SUPPORTED_KINDS.has(driverConfig.kind)) throw new Error(`agent '${name}' sets model but driver '${driver}' does not support model`); } d = { ...(x.effort === undefined ? {} : { effort: choice(x.effort, ["low", "medium", "high"], "effort") }), ...(x.timeoutSeconds === undefined ? {} : { timeoutSeconds: positive(x.timeoutSeconds, "timeoutSeconds") }), ...(model === undefined ? {} : { model }) }; } const customAgent = customizationName(a.agent, "agent.agent"); const requiredSkill = customizationName(a.requiredSkill, "agent.requiredSkill"); return { name, label: string(a.label, "agent.label"), description: string(a.description, "agent.description"), driver, purposes: a.purposes, policy: policy(a.policy), promptContract: string(a.promptContract, "promptContract"), ...(customAgent === undefined ? {} : { agent: customAgent }), ...(requiredSkill === undefined ? {} : { requiredSkill }), ...(d === undefined ? {} : { defaults: d }), enabled: a.enabled }; });
 let allowedWorkspaceRoots: readonly string[] | undefined; if (root.allowedWorkspaceRoots !== undefined) { if (!Array.isArray(root.allowedWorkspaceRoots) || root.allowedWorkspaceRoots.some((x) => typeof x !== "string" || x.length === 0)) throw new Error("allowedWorkspaceRoots must be strings"); allowedWorkspaceRoots = root.allowedWorkspaceRoots; } return { version: 1, defaults, ...(allowedWorkspaceRoots === undefined ? {} : { allowedWorkspaceRoots }), drivers, agents };
}
